name: What Matters
favicon: null
layout_spectrum: 0.9695816305465996
typography_spectrum: 0.20456062396988273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#242424'
    - '#606060'
    - '#d9d9d9'
    - '#b5b5b5'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
